#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Genealogy")]
	public partial class Linq2SqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGenderIndex(GenderIndex instance);
    partial void UpdateGenderIndex(GenderIndex instance);
    partial void DeleteGenderIndex(GenderIndex instance);
    partial void InsertRaceIndex(RaceIndex instance);
    partial void UpdateRaceIndex(RaceIndex instance);
    partial void DeleteRaceIndex(RaceIndex instance);
    partial void InsertGenderMatch(GenderMatch instance);
    partial void UpdateGenderMatch(GenderMatch instance);
    partial void DeleteGenderMatch(GenderMatch instance);
    partial void InsertRaceMatch(RaceMatch instance);
    partial void UpdateRaceMatch(RaceMatch instance);
    partial void DeleteRaceMatch(RaceMatch instance);
    partial void InsertIllinoisDeathIndexPost1915(IllinoisDeathIndexPost1915 instance);
    partial void UpdateIllinoisDeathIndexPost1915(IllinoisDeathIndexPost1915 instance);
    partial void DeleteIllinoisDeathIndexPost1915(IllinoisDeathIndexPost1915 instance);
    partial void InsertIllinoisDeathIndexPre1916(IllinoisDeathIndexPre1916 instance);
    partial void UpdateIllinoisDeathIndexPre1916(IllinoisDeathIndexPre1916 instance);
    partial void DeleteIllinoisDeathIndexPre1916(IllinoisDeathIndexPre1916 instance);
    partial void InsertDHDeathIndex(DHDeathIndex instance);
    partial void UpdateDHDeathIndex(DHDeathIndex instance);
    partial void DeleteDHDeathIndex(DHDeathIndex instance);
    partial void InsertKrestniJmena(KrestniJmena instance);
    partial void UpdateKrestniJmena(KrestniJmena instance);
    partial void DeleteKrestniJmena(KrestniJmena instance);
    partial void InsertIllinoisDeathIndexSearchesPre1916(IllinoisDeathIndexSearchesPre1916 instance);
    partial void UpdateIllinoisDeathIndexSearchesPre1916(IllinoisDeathIndexSearchesPre1916 instance);
    partial void DeleteIllinoisDeathIndexSearchesPre1916(IllinoisDeathIndexSearchesPre1916 instance);
    partial void InsertIllinoisDeathIndexSearchesPost1915(IllinoisDeathIndexSearchesPost1915 instance);
    partial void UpdateIllinoisDeathIndexSearchesPost1915(IllinoisDeathIndexSearchesPost1915 instance);
    partial void DeleteIllinoisDeathIndexSearchesPost1915(IllinoisDeathIndexSearchesPost1915 instance);
    partial void InsertPrijmeni(Prijmeni instance);
    partial void UpdatePrijmeni(Prijmeni instance);
    partial void DeletePrijmeni(Prijmeni instance);
    #endregion
		
		public Linq2SqlDataContext() : 
				base(global::dbAccess.Properties.Settings.Default.GenealogyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GenderIndex> GenderIndexes
		{
			get
			{
				return this.GetTable<GenderIndex>();
			}
		}
		
		public System.Data.Linq.Table<RaceIndex> RaceIndexes
		{
			get
			{
				return this.GetTable<RaceIndex>();
			}
		}
		
		public System.Data.Linq.Table<GenderMatch> GenderMatches
		{
			get
			{
				return this.GetTable<GenderMatch>();
			}
		}
		
		public System.Data.Linq.Table<RaceMatch> RaceMatches
		{
			get
			{
				return this.GetTable<RaceMatch>();
			}
		}
		
		public System.Data.Linq.Table<DHIllinoisPost1915Match> DHIllinoisPost1915Matches
		{
			get
			{
				return this.GetTable<DHIllinoisPost1915Match>();
			}
		}
		
		public System.Data.Linq.Table<DHIllinoisPre1916Match> DHIllinoisPre1916Matches
		{
			get
			{
				return this.GetTable<DHIllinoisPre1916Match>();
			}
		}
		
		public System.Data.Linq.Table<IllinoisDeathIndexPost1915> IllinoisDeathIndexPost1915s
		{
			get
			{
				return this.GetTable<IllinoisDeathIndexPost1915>();
			}
		}
		
		public System.Data.Linq.Table<IllinoisDeathIndexPre1916> IllinoisDeathIndexPre1916s
		{
			get
			{
				return this.GetTable<IllinoisDeathIndexPre1916>();
			}
		}
		
		public System.Data.Linq.Table<DHDeathIndex> DHDeathIndexes
		{
			get
			{
				return this.GetTable<DHDeathIndex>();
			}
		}
		
		public System.Data.Linq.Table<GivenNameEquivalent> GivenNameEquivalents
		{
			get
			{
				return this.GetTable<GivenNameEquivalent>();
			}
		}
		
		public System.Data.Linq.Table<KrestniJmena> KrestniJmenas
		{
			get
			{
				return this.GetTable<KrestniJmena>();
			}
		}
		
		public System.Data.Linq.Table<IllinoisDeathIndexSearchesPre1916> IllinoisDeathIndexSearchesPre1916s
		{
			get
			{
				return this.GetTable<IllinoisDeathIndexSearchesPre1916>();
			}
		}
		
		public System.Data.Linq.Table<IllinoisDeathIndexSearchHitsPre1916> IllinoisDeathIndexSearchHitsPre1916s
		{
			get
			{
				return this.GetTable<IllinoisDeathIndexSearchHitsPre1916>();
			}
		}
		
		public System.Data.Linq.Table<IllinoisDeathIndexSearchesPost1915> IllinoisDeathIndexSearchesPost1915s
		{
			get
			{
				return this.GetTable<IllinoisDeathIndexSearchesPost1915>();
			}
		}
		
		public System.Data.Linq.Table<IllinoisDeathIndexSearchHitsPost1915> IllinoisDeathIndexSearchHitsPost1915s
		{
			get
			{
				return this.GetTable<IllinoisDeathIndexSearchHitsPost1915>();
			}
		}
		
		public System.Data.Linq.Table<Prijmeni> Prijmenis
		{
			get
			{
				return this.GetTable<Prijmeni>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GenderIndex")]
	public partial class GenderIndex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Serial;
		
		private string _Description;
		
		private EntitySet<GenderMatch> _GenderMatches;
		
		private EntitySet<IllinoisDeathIndexPost1915> _IllinoisDeathIndexPost1915s;
		
		private EntitySet<IllinoisDeathIndexPre1916> _IllinoisDeathIndexPre1916s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSerialChanging(short value);
    partial void OnSerialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public GenderIndex()
		{
			this._GenderMatches = new EntitySet<GenderMatch>(new Action<GenderMatch>(this.attach_GenderMatches), new Action<GenderMatch>(this.detach_GenderMatches));
			this._IllinoisDeathIndexPost1915s = new EntitySet<IllinoisDeathIndexPost1915>(new Action<IllinoisDeathIndexPost1915>(this.attach_IllinoisDeathIndexPost1915s), new Action<IllinoisDeathIndexPost1915>(this.detach_IllinoisDeathIndexPost1915s));
			this._IllinoisDeathIndexPre1916s = new EntitySet<IllinoisDeathIndexPre1916>(new Action<IllinoisDeathIndexPre1916>(this.attach_IllinoisDeathIndexPre1916s), new Action<IllinoisDeathIndexPre1916>(this.detach_IllinoisDeathIndexPre1916s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short Serial
		{
			get
			{
				return this._Serial;
			}
			set
			{
				if ((this._Serial != value))
				{
					this.OnSerialChanging(value);
					this.SendPropertyChanging();
					this._Serial = value;
					this.SendPropertyChanged("Serial");
					this.OnSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GenderIndex_GenderMatch", Storage="_GenderMatches", ThisKey="Serial", OtherKey="GenderIndex")]
		public EntitySet<GenderMatch> GenderMatches
		{
			get
			{
				return this._GenderMatches;
			}
			set
			{
				this._GenderMatches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GenderIndex_IllinoisDeathIndexPost1915", Storage="_IllinoisDeathIndexPost1915s", ThisKey="Serial", OtherKey="GenderIndex")]
		public EntitySet<IllinoisDeathIndexPost1915> IllinoisDeathIndexPost1915s
		{
			get
			{
				return this._IllinoisDeathIndexPost1915s;
			}
			set
			{
				this._IllinoisDeathIndexPost1915s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GenderIndex_IllinoisDeathIndexPre1916", Storage="_IllinoisDeathIndexPre1916s", ThisKey="Serial", OtherKey="GenderIndex")]
		public EntitySet<IllinoisDeathIndexPre1916> IllinoisDeathIndexPre1916s
		{
			get
			{
				return this._IllinoisDeathIndexPre1916s;
			}
			set
			{
				this._IllinoisDeathIndexPre1916s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GenderMatches(GenderMatch entity)
		{
			this.SendPropertyChanging();
			entity.GenderIndex1 = this;
		}
		
		private void detach_GenderMatches(GenderMatch entity)
		{
			this.SendPropertyChanging();
			entity.GenderIndex1 = null;
		}
		
		private void attach_IllinoisDeathIndexPost1915s(IllinoisDeathIndexPost1915 entity)
		{
			this.SendPropertyChanging();
			entity.GenderIndex1 = this;
		}
		
		private void detach_IllinoisDeathIndexPost1915s(IllinoisDeathIndexPost1915 entity)
		{
			this.SendPropertyChanging();
			entity.GenderIndex1 = null;
		}
		
		private void attach_IllinoisDeathIndexPre1916s(IllinoisDeathIndexPre1916 entity)
		{
			this.SendPropertyChanging();
			entity.GenderIndex1 = this;
		}
		
		private void detach_IllinoisDeathIndexPre1916s(IllinoisDeathIndexPre1916 entity)
		{
			this.SendPropertyChanging();
			entity.GenderIndex1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RaceIndex")]
	public partial class RaceIndex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Serial;
		
		private string _Description;
		
		private EntitySet<RaceMatch> _RaceMatches;
		
		private EntitySet<IllinoisDeathIndexPost1915> _IllinoisDeathIndexPost1915s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSerialChanging(short value);
    partial void OnSerialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public RaceIndex()
		{
			this._RaceMatches = new EntitySet<RaceMatch>(new Action<RaceMatch>(this.attach_RaceMatches), new Action<RaceMatch>(this.detach_RaceMatches));
			this._IllinoisDeathIndexPost1915s = new EntitySet<IllinoisDeathIndexPost1915>(new Action<IllinoisDeathIndexPost1915>(this.attach_IllinoisDeathIndexPost1915s), new Action<IllinoisDeathIndexPost1915>(this.detach_IllinoisDeathIndexPost1915s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short Serial
		{
			get
			{
				return this._Serial;
			}
			set
			{
				if ((this._Serial != value))
				{
					this.OnSerialChanging(value);
					this.SendPropertyChanging();
					this._Serial = value;
					this.SendPropertyChanged("Serial");
					this.OnSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RaceIndex_RaceMatch", Storage="_RaceMatches", ThisKey="Serial", OtherKey="RaceIndex")]
		public EntitySet<RaceMatch> RaceMatches
		{
			get
			{
				return this._RaceMatches;
			}
			set
			{
				this._RaceMatches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RaceIndex_IllinoisDeathIndexPost1915", Storage="_IllinoisDeathIndexPost1915s", ThisKey="Serial", OtherKey="RaceIndex")]
		public EntitySet<IllinoisDeathIndexPost1915> IllinoisDeathIndexPost1915s
		{
			get
			{
				return this._IllinoisDeathIndexPost1915s;
			}
			set
			{
				this._IllinoisDeathIndexPost1915s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RaceMatches(RaceMatch entity)
		{
			this.SendPropertyChanging();
			entity.RaceIndex1 = this;
		}
		
		private void detach_RaceMatches(RaceMatch entity)
		{
			this.SendPropertyChanging();
			entity.RaceIndex1 = null;
		}
		
		private void attach_IllinoisDeathIndexPost1915s(IllinoisDeathIndexPost1915 entity)
		{
			this.SendPropertyChanging();
			entity.RaceIndex1 = this;
		}
		
		private void detach_IllinoisDeathIndexPost1915s(IllinoisDeathIndexPost1915 entity)
		{
			this.SendPropertyChanging();
			entity.RaceIndex1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GenderMatch")]
	public partial class GenderMatch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mnemonic;
		
		private short _GenderIndex;
		
		private EntityRef<GenderIndex> _GenderIndex1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMnemonicChanging(string value);
    partial void OnMnemonicChanged();
    partial void OnGenderIndexChanging(short value);
    partial void OnGenderIndexChanged();
    #endregion
		
		public GenderMatch()
		{
			this._GenderIndex1 = default(EntityRef<GenderIndex>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mnemonic", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mnemonic
		{
			get
			{
				return this._Mnemonic;
			}
			set
			{
				if ((this._Mnemonic != value))
				{
					this.OnMnemonicChanging(value);
					this.SendPropertyChanging();
					this._Mnemonic = value;
					this.SendPropertyChanged("Mnemonic");
					this.OnMnemonicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderIndex", DbType="SmallInt NOT NULL")]
		public short GenderIndex
		{
			get
			{
				return this._GenderIndex;
			}
			set
			{
				if ((this._GenderIndex != value))
				{
					if (this._GenderIndex1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGenderIndexChanging(value);
					this.SendPropertyChanging();
					this._GenderIndex = value;
					this.SendPropertyChanged("GenderIndex");
					this.OnGenderIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GenderIndex_GenderMatch", Storage="_GenderIndex1", ThisKey="GenderIndex", OtherKey="Serial", IsForeignKey=true)]
		public GenderIndex GenderIndex1
		{
			get
			{
				return this._GenderIndex1.Entity;
			}
			set
			{
				GenderIndex previousValue = this._GenderIndex1.Entity;
				if (((previousValue != value) 
							|| (this._GenderIndex1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GenderIndex1.Entity = null;
						previousValue.GenderMatches.Remove(this);
					}
					this._GenderIndex1.Entity = value;
					if ((value != null))
					{
						value.GenderMatches.Add(this);
						this._GenderIndex = value.Serial;
					}
					else
					{
						this._GenderIndex = default(short);
					}
					this.SendPropertyChanged("GenderIndex1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RaceMatch")]
	public partial class RaceMatch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mnemonic;
		
		private short _RaceIndex;
		
		private EntityRef<RaceIndex> _RaceIndex1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMnemonicChanging(string value);
    partial void OnMnemonicChanged();
    partial void OnRaceIndexChanging(short value);
    partial void OnRaceIndexChanged();
    #endregion
		
		public RaceMatch()
		{
			this._RaceIndex1 = default(EntityRef<RaceIndex>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mnemonic", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mnemonic
		{
			get
			{
				return this._Mnemonic;
			}
			set
			{
				if ((this._Mnemonic != value))
				{
					this.OnMnemonicChanging(value);
					this.SendPropertyChanging();
					this._Mnemonic = value;
					this.SendPropertyChanged("Mnemonic");
					this.OnMnemonicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaceIndex", DbType="SmallInt NOT NULL")]
		public short RaceIndex
		{
			get
			{
				return this._RaceIndex;
			}
			set
			{
				if ((this._RaceIndex != value))
				{
					if (this._RaceIndex1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRaceIndexChanging(value);
					this.SendPropertyChanging();
					this._RaceIndex = value;
					this.SendPropertyChanged("RaceIndex");
					this.OnRaceIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RaceIndex_RaceMatch", Storage="_RaceIndex1", ThisKey="RaceIndex", OtherKey="Serial", IsForeignKey=true)]
		public RaceIndex RaceIndex1
		{
			get
			{
				return this._RaceIndex1.Entity;
			}
			set
			{
				RaceIndex previousValue = this._RaceIndex1.Entity;
				if (((previousValue != value) 
							|| (this._RaceIndex1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RaceIndex1.Entity = null;
						previousValue.RaceMatches.Remove(this);
					}
					this._RaceIndex1.Entity = value;
					if ((value != null))
					{
						value.RaceMatches.Add(this);
						this._RaceIndex = value.Serial;
					}
					else
					{
						this._RaceIndex = default(short);
					}
					this.SendPropertyChanged("RaceIndex1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DHIllinoisPost1915Match")]
	public partial class DHIllinoisPost1915Match
	{
		
		private int _HlasatelIndex;
		
		private int _IllinoisDeathIndex;
		
		public DHIllinoisPost1915Match()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HlasatelIndex", DbType="Int NOT NULL")]
		public int HlasatelIndex
		{
			get
			{
				return this._HlasatelIndex;
			}
			set
			{
				if ((this._HlasatelIndex != value))
				{
					this._HlasatelIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IllinoisDeathIndex", DbType="Int NOT NULL")]
		public int IllinoisDeathIndex
		{
			get
			{
				return this._IllinoisDeathIndex;
			}
			set
			{
				if ((this._IllinoisDeathIndex != value))
				{
					this._IllinoisDeathIndex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DHIllinoisPre1916Match")]
	public partial class DHIllinoisPre1916Match
	{
		
		private int _HlasatelIndex;
		
		private int _IllinoisDeathIndex;
		
		public DHIllinoisPre1916Match()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HlasatelIndex", DbType="Int NOT NULL")]
		public int HlasatelIndex
		{
			get
			{
				return this._HlasatelIndex;
			}
			set
			{
				if ((this._HlasatelIndex != value))
				{
					this._HlasatelIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IllinoisDeathIndex", DbType="Int NOT NULL")]
		public int IllinoisDeathIndex
		{
			get
			{
				return this._IllinoisDeathIndex;
			}
			set
			{
				if ((this._IllinoisDeathIndex != value))
				{
					this._IllinoisDeathIndex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IllinoisDeathIndexPost1915")]
	public partial class IllinoisDeathIndexPost1915 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Surname;
		
		private string _GivenName;
		
		private string _MiddleName;
		
		private short _GenderIndex;
		
		private short _RaceIndex;
		
		private short _AgeInYears;
		
		private int _CertificateNumber;
		
		private System.DateTime _DeathDate;
		
		private string _County;
		
		private string _City;
		
		private System.DateTime _ReportDate;
		
		private int _Serial;
		
		private EntityRef<GenderIndex> _GenderIndex1;
		
		private EntityRef<RaceIndex> _RaceIndex1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnGenderIndexChanging(short value);
    partial void OnGenderIndexChanged();
    partial void OnRaceIndexChanging(short value);
    partial void OnRaceIndexChanged();
    partial void OnAgeInYearsChanging(short value);
    partial void OnAgeInYearsChanged();
    partial void OnCertificateNumberChanging(int value);
    partial void OnCertificateNumberChanged();
    partial void OnDeathDateChanging(System.DateTime value);
    partial void OnDeathDateChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnReportDateChanging(System.DateTime value);
    partial void OnReportDateChanged();
    partial void OnSerialChanging(int value);
    partial void OnSerialChanged();
    #endregion
		
		public IllinoisDeathIndexPost1915()
		{
			this._GenderIndex1 = default(EntityRef<GenderIndex>);
			this._RaceIndex1 = default(EntityRef<RaceIndex>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderIndex", DbType="SmallInt NOT NULL")]
		public short GenderIndex
		{
			get
			{
				return this._GenderIndex;
			}
			set
			{
				if ((this._GenderIndex != value))
				{
					if (this._GenderIndex1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGenderIndexChanging(value);
					this.SendPropertyChanging();
					this._GenderIndex = value;
					this.SendPropertyChanged("GenderIndex");
					this.OnGenderIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaceIndex", DbType="SmallInt NOT NULL")]
		public short RaceIndex
		{
			get
			{
				return this._RaceIndex;
			}
			set
			{
				if ((this._RaceIndex != value))
				{
					if (this._RaceIndex1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRaceIndexChanging(value);
					this.SendPropertyChanging();
					this._RaceIndex = value;
					this.SendPropertyChanged("RaceIndex");
					this.OnRaceIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeInYears", DbType="SmallInt NOT NULL")]
		public short AgeInYears
		{
			get
			{
				return this._AgeInYears;
			}
			set
			{
				if ((this._AgeInYears != value))
				{
					this.OnAgeInYearsChanging(value);
					this.SendPropertyChanging();
					this._AgeInYears = value;
					this.SendPropertyChanged("AgeInYears");
					this.OnAgeInYearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateNumber", DbType="Int NOT NULL")]
		public int CertificateNumber
		{
			get
			{
				return this._CertificateNumber;
			}
			set
			{
				if ((this._CertificateNumber != value))
				{
					this.OnCertificateNumberChanging(value);
					this.SendPropertyChanging();
					this._CertificateNumber = value;
					this.SendPropertyChanged("CertificateNumber");
					this.OnCertificateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeathDate", DbType="Date NOT NULL")]
		public System.DateTime DeathDate
		{
			get
			{
				return this._DeathDate;
			}
			set
			{
				if ((this._DeathDate != value))
				{
					this.OnDeathDateChanging(value);
					this.SendPropertyChanging();
					this._DeathDate = value;
					this.SendPropertyChanged("DeathDate");
					this.OnDeathDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportDate", DbType="Date NOT NULL")]
		public System.DateTime ReportDate
		{
			get
			{
				return this._ReportDate;
			}
			set
			{
				if ((this._ReportDate != value))
				{
					this.OnReportDateChanging(value);
					this.SendPropertyChanging();
					this._ReportDate = value;
					this.SendPropertyChanged("ReportDate");
					this.OnReportDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Serial
		{
			get
			{
				return this._Serial;
			}
			set
			{
				if ((this._Serial != value))
				{
					this.OnSerialChanging(value);
					this.SendPropertyChanging();
					this._Serial = value;
					this.SendPropertyChanged("Serial");
					this.OnSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GenderIndex_IllinoisDeathIndexPost1915", Storage="_GenderIndex1", ThisKey="GenderIndex", OtherKey="Serial", IsForeignKey=true)]
		public GenderIndex GenderIndex1
		{
			get
			{
				return this._GenderIndex1.Entity;
			}
			set
			{
				GenderIndex previousValue = this._GenderIndex1.Entity;
				if (((previousValue != value) 
							|| (this._GenderIndex1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GenderIndex1.Entity = null;
						previousValue.IllinoisDeathIndexPost1915s.Remove(this);
					}
					this._GenderIndex1.Entity = value;
					if ((value != null))
					{
						value.IllinoisDeathIndexPost1915s.Add(this);
						this._GenderIndex = value.Serial;
					}
					else
					{
						this._GenderIndex = default(short);
					}
					this.SendPropertyChanged("GenderIndex1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RaceIndex_IllinoisDeathIndexPost1915", Storage="_RaceIndex1", ThisKey="RaceIndex", OtherKey="Serial", IsForeignKey=true)]
		public RaceIndex RaceIndex1
		{
			get
			{
				return this._RaceIndex1.Entity;
			}
			set
			{
				RaceIndex previousValue = this._RaceIndex1.Entity;
				if (((previousValue != value) 
							|| (this._RaceIndex1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RaceIndex1.Entity = null;
						previousValue.IllinoisDeathIndexPost1915s.Remove(this);
					}
					this._RaceIndex1.Entity = value;
					if ((value != null))
					{
						value.IllinoisDeathIndexPost1915s.Add(this);
						this._RaceIndex = value.Serial;
					}
					else
					{
						this._RaceIndex = default(short);
					}
					this.SendPropertyChanged("RaceIndex1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IllinoisDeathIndexPre1916")]
	public partial class IllinoisDeathIndexPre1916 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _certificateNumber;
		
		private string _Surname;
		
		private string _GivenName;
		
		private string _MiddleName;
		
		private System.DateTime _deathDate;
		
		private short _ageInYears;
		
		private short _GenderIndex;
		
		private string _city;
		
		private string _county;
		
		private string _volume;
		
		private short _page;
		
		private int _serial;
		
		private EntityRef<GenderIndex> _GenderIndex1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncertificateNumberChanging(int value);
    partial void OncertificateNumberChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OndeathDateChanging(System.DateTime value);
    partial void OndeathDateChanged();
    partial void OnageInYearsChanging(short value);
    partial void OnageInYearsChanged();
    partial void OnGenderIndexChanging(short value);
    partial void OnGenderIndexChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OncountyChanging(string value);
    partial void OncountyChanged();
    partial void OnvolumeChanging(string value);
    partial void OnvolumeChanged();
    partial void OnpageChanging(short value);
    partial void OnpageChanged();
    partial void OnserialChanging(int value);
    partial void OnserialChanged();
    #endregion
		
		public IllinoisDeathIndexPre1916()
		{
			this._GenderIndex1 = default(EntityRef<GenderIndex>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificateNumber", DbType="Int NOT NULL")]
		public int certificateNumber
		{
			get
			{
				return this._certificateNumber;
			}
			set
			{
				if ((this._certificateNumber != value))
				{
					this.OncertificateNumberChanging(value);
					this.SendPropertyChanging();
					this._certificateNumber = value;
					this.SendPropertyChanged("certificateNumber");
					this.OncertificateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deathDate", DbType="Date NOT NULL")]
		public System.DateTime deathDate
		{
			get
			{
				return this._deathDate;
			}
			set
			{
				if ((this._deathDate != value))
				{
					this.OndeathDateChanging(value);
					this.SendPropertyChanging();
					this._deathDate = value;
					this.SendPropertyChanged("deathDate");
					this.OndeathDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ageInYears", DbType="SmallInt NOT NULL")]
		public short ageInYears
		{
			get
			{
				return this._ageInYears;
			}
			set
			{
				if ((this._ageInYears != value))
				{
					this.OnageInYearsChanging(value);
					this.SendPropertyChanging();
					this._ageInYears = value;
					this.SendPropertyChanged("ageInYears");
					this.OnageInYearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderIndex", DbType="SmallInt NOT NULL")]
		public short GenderIndex
		{
			get
			{
				return this._GenderIndex;
			}
			set
			{
				if ((this._GenderIndex != value))
				{
					if (this._GenderIndex1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGenderIndexChanging(value);
					this.SendPropertyChanging();
					this._GenderIndex = value;
					this.SendPropertyChanged("GenderIndex");
					this.OnGenderIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_county", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string county
		{
			get
			{
				return this._county;
			}
			set
			{
				if ((this._county != value))
				{
					this.OncountyChanging(value);
					this.SendPropertyChanging();
					this._county = value;
					this.SendPropertyChanged("county");
					this.OncountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page", DbType="SmallInt NOT NULL")]
		public short page
		{
			get
			{
				return this._page;
			}
			set
			{
				if ((this._page != value))
				{
					this.OnpageChanging(value);
					this.SendPropertyChanging();
					this._page = value;
					this.SendPropertyChanged("page");
					this.OnpageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int serial
		{
			get
			{
				return this._serial;
			}
			set
			{
				if ((this._serial != value))
				{
					this.OnserialChanging(value);
					this.SendPropertyChanging();
					this._serial = value;
					this.SendPropertyChanged("serial");
					this.OnserialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GenderIndex_IllinoisDeathIndexPre1916", Storage="_GenderIndex1", ThisKey="GenderIndex", OtherKey="Serial", IsForeignKey=true)]
		public GenderIndex GenderIndex1
		{
			get
			{
				return this._GenderIndex1.Entity;
			}
			set
			{
				GenderIndex previousValue = this._GenderIndex1.Entity;
				if (((previousValue != value) 
							|| (this._GenderIndex1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GenderIndex1.Entity = null;
						previousValue.IllinoisDeathIndexPre1916s.Remove(this);
					}
					this._GenderIndex1.Entity = value;
					if ((value != null))
					{
						value.IllinoisDeathIndexPre1916s.Add(this);
						this._GenderIndex = value.Serial;
					}
					else
					{
						this._GenderIndex = default(short);
					}
					this.SendPropertyChanged("GenderIndex1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DHDeathIndex")]
	public partial class DHDeathIndex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Surname;
		
		private string _GivenName;
		
		private System.DateTime _ReportDate;
		
		private int _serial;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnReportDateChanging(System.DateTime value);
    partial void OnReportDateChanged();
    partial void OnserialChanging(int value);
    partial void OnserialChanged();
    #endregion
		
		public DHDeathIndex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportDate", DbType="Date NOT NULL")]
		public System.DateTime ReportDate
		{
			get
			{
				return this._ReportDate;
			}
			set
			{
				if ((this._ReportDate != value))
				{
					this.OnReportDateChanging(value);
					this.SendPropertyChanging();
					this._ReportDate = value;
					this.SendPropertyChanged("ReportDate");
					this.OnReportDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int serial
		{
			get
			{
				return this._serial;
			}
			set
			{
				if ((this._serial != value))
				{
					this.OnserialChanging(value);
					this.SendPropertyChanging();
					this._serial = value;
					this.SendPropertyChanged("serial");
					this.OnserialChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GivenNameEquivalents")]
	public partial class GivenNameEquivalent
	{
		
		private string _English;
		
		private string _Native;
		
		public GivenNameEquivalent()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string English
		{
			get
			{
				return this._English;
			}
			set
			{
				if ((this._English != value))
				{
					this._English = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Native", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Native
		{
			get
			{
				return this._Native;
			}
			set
			{
				if ((this._Native != value))
				{
					this._Native = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KrestniJmena")]
	public partial class KrestniJmena : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodePage;
		
		private string _Web;
		
		private string _PlainText;
		
		private int _MaleCount;
		
		private int _MaleIndex;
		
		private int _FemaleCount;
		
		private int _FemaleIndex;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodePageChanging(string value);
    partial void OnCodePageChanged();
    partial void OnWebChanging(string value);
    partial void OnWebChanged();
    partial void OnPlainTextChanging(string value);
    partial void OnPlainTextChanged();
    partial void OnMaleCountChanging(int value);
    partial void OnMaleCountChanged();
    partial void OnMaleIndexChanging(int value);
    partial void OnMaleIndexChanged();
    partial void OnFemaleCountChanging(int value);
    partial void OnFemaleCountChanged();
    partial void OnFemaleIndexChanging(int value);
    partial void OnFemaleIndexChanged();
    #endregion
		
		public KrestniJmena()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePage", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodePage
		{
			get
			{
				return this._CodePage;
			}
			set
			{
				if ((this._CodePage != value))
				{
					this.OnCodePageChanging(value);
					this.SendPropertyChanging();
					this._CodePage = value;
					this.SendPropertyChanged("CodePage");
					this.OnCodePageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this.OnWebChanging(value);
					this.SendPropertyChanging();
					this._Web = value;
					this.SendPropertyChanged("Web");
					this.OnWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlainText", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PlainText
		{
			get
			{
				return this._PlainText;
			}
			set
			{
				if ((this._PlainText != value))
				{
					this.OnPlainTextChanging(value);
					this.SendPropertyChanging();
					this._PlainText = value;
					this.SendPropertyChanged("PlainText");
					this.OnPlainTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaleCount", DbType="Int NOT NULL")]
		public int MaleCount
		{
			get
			{
				return this._MaleCount;
			}
			set
			{
				if ((this._MaleCount != value))
				{
					this.OnMaleCountChanging(value);
					this.SendPropertyChanging();
					this._MaleCount = value;
					this.SendPropertyChanged("MaleCount");
					this.OnMaleCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaleIndex", DbType="Int NOT NULL")]
		public int MaleIndex
		{
			get
			{
				return this._MaleIndex;
			}
			set
			{
				if ((this._MaleIndex != value))
				{
					this.OnMaleIndexChanging(value);
					this.SendPropertyChanging();
					this._MaleIndex = value;
					this.SendPropertyChanged("MaleIndex");
					this.OnMaleIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FemaleCount", DbType="Int NOT NULL")]
		public int FemaleCount
		{
			get
			{
				return this._FemaleCount;
			}
			set
			{
				if ((this._FemaleCount != value))
				{
					this.OnFemaleCountChanging(value);
					this.SendPropertyChanging();
					this._FemaleCount = value;
					this.SendPropertyChanged("FemaleCount");
					this.OnFemaleCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FemaleIndex", DbType="Int NOT NULL")]
		public int FemaleIndex
		{
			get
			{
				return this._FemaleIndex;
			}
			set
			{
				if ((this._FemaleIndex != value))
				{
					this.OnFemaleIndexChanging(value);
					this.SendPropertyChanging();
					this._FemaleIndex = value;
					this.SendPropertyChanged("FemaleIndex");
					this.OnFemaleIndexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IllinoisDeathIndexSearchesPre1916")]
	public partial class IllinoisDeathIndexSearchesPre1916 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Surname;
		
		private string _GivenName;
		
		private string _MiddleName;
		
		private string _County;
		
		private int _serial;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnserialChanging(int value);
    partial void OnserialChanged();
    #endregion
		
		public IllinoisDeathIndexSearchesPre1916()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int serial
		{
			get
			{
				return this._serial;
			}
			set
			{
				if ((this._serial != value))
				{
					this.OnserialChanging(value);
					this.SendPropertyChanging();
					this._serial = value;
					this.SendPropertyChanged("serial");
					this.OnserialChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IllinoisDeathIndexSearchHitsPre1916")]
	public partial class IllinoisDeathIndexSearchHitsPre1916
	{
		
		private int _SearchIndex;
		
		private int _RecordIndex;
		
		public IllinoisDeathIndexSearchHitsPre1916()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchIndex", DbType="Int NOT NULL")]
		public int SearchIndex
		{
			get
			{
				return this._SearchIndex;
			}
			set
			{
				if ((this._SearchIndex != value))
				{
					this._SearchIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordIndex", DbType="Int NOT NULL")]
		public int RecordIndex
		{
			get
			{
				return this._RecordIndex;
			}
			set
			{
				if ((this._RecordIndex != value))
				{
					this._RecordIndex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IllinoisDeathIndexSearchesPost1915")]
	public partial class IllinoisDeathIndexSearchesPost1915 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Surname;
		
		private string _GivenName;
		
		private string _MiddleName;
		
		private string _County;
		
		private int _serial;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnserialChanging(int value);
    partial void OnserialChanged();
    #endregion
		
		public IllinoisDeathIndexSearchesPost1915()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int serial
		{
			get
			{
				return this._serial;
			}
			set
			{
				if ((this._serial != value))
				{
					this.OnserialChanging(value);
					this.SendPropertyChanging();
					this._serial = value;
					this.SendPropertyChanged("serial");
					this.OnserialChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IllinoisDeathIndexSearchHitsPost1915")]
	public partial class IllinoisDeathIndexSearchHitsPost1915
	{
		
		private int _SearchIndex;
		
		private int _RecordIndex;
		
		public IllinoisDeathIndexSearchHitsPost1915()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchIndex", DbType="Int NOT NULL")]
		public int SearchIndex
		{
			get
			{
				return this._SearchIndex;
			}
			set
			{
				if ((this._SearchIndex != value))
				{
					this._SearchIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordIndex", DbType="Int NOT NULL")]
		public int RecordIndex
		{
			get
			{
				return this._RecordIndex;
			}
			set
			{
				if ((this._RecordIndex != value))
				{
					this._RecordIndex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prijmeni")]
	public partial class Prijmeni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Rank;
		
		private string _Iso8859;
		
		private string _Windows;
		
		private string _Web;
		
		private string _PlainText;
		
		private int _Count;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRankChanging(int value);
    partial void OnRankChanged();
    partial void OnIso8859Changing(string value);
    partial void OnIso8859Changed();
    partial void OnWindowsChanging(string value);
    partial void OnWindowsChanged();
    partial void OnWebChanging(string value);
    partial void OnWebChanged();
    partial void OnPlainTextChanging(string value);
    partial void OnPlainTextChanged();
    partial void OnCountChanging(int value);
    partial void OnCountChanged();
    #endregion
		
		public Prijmeni()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this.OnRankChanging(value);
					this.SendPropertyChanging();
					this._Rank = value;
					this.SendPropertyChanged("Rank");
					this.OnRankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iso8859", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Iso8859
		{
			get
			{
				return this._Iso8859;
			}
			set
			{
				if ((this._Iso8859 != value))
				{
					this.OnIso8859Changing(value);
					this.SendPropertyChanging();
					this._Iso8859 = value;
					this.SendPropertyChanged("Iso8859");
					this.OnIso8859Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Windows", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Windows
		{
			get
			{
				return this._Windows;
			}
			set
			{
				if ((this._Windows != value))
				{
					this.OnWindowsChanging(value);
					this.SendPropertyChanging();
					this._Windows = value;
					this.SendPropertyChanged("Windows");
					this.OnWindowsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this.OnWebChanging(value);
					this.SendPropertyChanging();
					this._Web = value;
					this.SendPropertyChanged("Web");
					this.OnWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlainText", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PlainText
		{
			get
			{
				return this._PlainText;
			}
			set
			{
				if ((this._PlainText != value))
				{
					this.OnPlainTextChanging(value);
					this.SendPropertyChanging();
					this._PlainText = value;
					this.SendPropertyChanged("PlainText");
					this.OnPlainTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", DbType="Int NOT NULL")]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
